### ISSUE TITLE
Argument issue ?

### ISSUE THREAD

**Issue by TH3xACE** [CravateRouge/bloodyAD#2]
python3 bloodyAD.py -d marvel.com -u ironman -p "Pass123" --host 192.168.102.101 getGroupMembers -identity spiderman

Error > bloodyAD.py: error: unrecognized arguments: -identity

python3 bloodyAD.py -d marvel.com -u ironman -p "Pass123" --host 192.168.102.101 getGroupMembers identity spiderman

Error > You provided too many arguments

**Comment by CravateRouge** [comment]
It should be:
```
python3 bloodyAD.py -d marvel.com -u ironman -p "Pass123" --host 192.168.102.101 getGroupMembers [Name of the Group]
```
The functions' arguments are positional so you must not give an option name as `-identity` before.
`getGroupMembers` and some other functions don't have a complete documentation yet.

PS: `getGroupMembers` gives you the members of a group so you should provide `avengers` instead of `spiderman`

**Comment by TH3xACE** [comment]
Oh! I see my bad... Thanks... working fine ;)
